# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Home About
  description: About Section
  icon: 'cottage'
  tags: ['block', 'hero']

# Defines the structure of this component, as well as the default values
blueprint:
  h2:
  p:
  altText:
  imagePath:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  width:
    type: number
  height:
    type: number
  icon:
    type: select
    options:
      values: data.icons
